- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install Python3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx

- name: Register certbot
  ansible.builtin.shell: |
    certbot -n register --agree-tos --email bonny.ophelie@gmail.com
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered

- name: Copy the Nginx configuration file to the host
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  
- name: Create link to the new config to enable it
  file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link
  notify: Restart the Nginx service

- name: 'Get certificate'
  ansible.builtin.command: 'certbot -n --nginx -d monitoring.batch7.online'
  args:
    creates: '/etc/letsencrypt/live/monitoring.batch7.online'

- name: Copy docker-compose folder
  ansible.builtin.copy:
    src: ../../../prometheus
    dest: /home/admin
  register: container

- name : 
