- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install Python3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx

- name: Ensure NGINX service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Copy NGINX and Prometheus configurations
  hosts: all
  become: yes

  vars:
    nginx_conf_src: ../templates/nginx.conf
    nginx_ssl_conf_src: ../templates/ssl.conf
    nginx_conf_d_src: ../templates/conf.d/
    nginx_conf_dest: /etc/nginx/nginx.conf
    nginx_ssl_conf_dest: /etc/nginx/conf.d/ssl.conf
    nginx_conf_d_dest: /etc/nginx/conf.d/

  tasks:
    - name: Copy nginx.conf
      copy:
        src: "{{ nginx_conf_src }}"
        dest: "{{ nginx_conf_dest }}"

    - name: Copy ssl.conf
      copy:
        src: "{{ nginx_ssl_conf_src }}"
        dest: "{{ nginx_ssl_conf_dest }}"

    - name: Copy NGINX configurations
      copy:
        src: "{{ item.src }}"
        dest: "{{ nginx_conf_d_dest }}{{ item.dest }}"
      loop:
        - { src: "{{ nginx_conf_d_src }}grafana.conf", dest: "grafana.conf" }
        - { src: "{{ nginx_conf_d_src }}prometheus.conf", dest: "prometheus.conf" }
        - { src: "{{ nginx_conf_d_src }}node-exporter.conf", dest: "node-exporter.conf" }
        - { src: "{{ nginx_conf_d_src }}cadvisor.conf", dest: "cadvisor.conf" }
        - { src: "{{ nginx_conf_d_src }}alertmanager.conf", dest: "alertmanager.conf" }

- name: Copy docker-compose folder
  ansible.builtin.copy:
    src: ../../../prometheus
    dest: /home/admin
