- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure NGINX service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Install Python3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx

- name: Register certbot
  ansible.builtin.shell: |
    certbot -n register --agree-tos --email bonny.ophelie@gmail.com
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered

- name: 'Get certificate'
  ansible.builtin.command: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/{{ item }}.key -out /etc/nginx/ssl/{{ item }}.crt"
  with_items:
      - grafana
      - prometheus
      - node-exporter
      - alertmanager
      - cadvisor

- name: Configure NGINX for {{ item }}
  template:
      src: nginx_{{ item }}.conf.j2
      dest: /etc/nginx/sites-available/{{ item }}
  with_items:
      - grafana
      - prometheus
      - node-exporter
      - alertmanager
      - cadvisor
    notify: Reload NGINX


- name: Copy docker-compose folder
  ansible.builtin.copy:
    src: ../../../prometheus
    dest: /home/admin
