- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install Python3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx

- name: Ensure NGINX service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Obtain SSL certificates using Certbot
  ansible.builtin.command: "certbot certonly --nginx -d {{ item }}"
  with_items:
    - grafana.batch7.online
    - prometheus.batch7.online
    - node-exporter.batch7.online
    - alertmanager.batch7.online
    - cadvisor.batch7.online

- name: Configure NGINX for {{ item }}
  ansible.builtin.template:
      src: nginx_{{ item }}.conf.j2
      dest: /etc/nginx/sites-available/{{ item }}
  with_items:
      - grafana
      - prometheus
      - node-exporter
      - alertmanager
      - cadvisor
    notify: Reload NGINX


- name: Copy docker-compose folder
  ansible.builtin.copy:
    src: ../../../prometheus
    dest: /home/admin
