- name: Start Caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: started
    enabled: yes

- name: Reload Caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: reloaded