sync-with-github:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - |
      if ! git remote | grep -q github; then
        git remote add github $REMOTE_REPOSITORY_URL
      fi
    - git checkout main
    - git pull origin main
    - git pull github main
    - |
      if git diff --quiet; then
        echo "No changes to push"
        exit 0
      else
        echo "Changes detected, pushing to GitLab"
        git push https://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
      fi
