- name: Installing Docker
  hosts: all
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: roles/docker

- name: Security rules
  hosts: all
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: roles/security

- name: OVH DNS
  hosts: all
  environment:
    OVH_ENDPOINT: "ovh-eu"
    OVH_APPLICATION_KEY: "$OVH_APPLICATION_KEY"
    OVH_APPLICATION_SECRET: "$OVH_APPLICATION_SECRET"
    OVH_CONSUMER_KEY: "$OVH_CONSUMER_KEY"

- name: Launch services
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create network letsencrypt
      community.docker.docker_network:
        name: letsencrypt

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: monitoring
        state: absent

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: monitoring