version: '3.7'

services:
  nginx-proxy:
   container_name: nginx
   image: jwilder/nginx-proxy
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./certs:/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

  grafana:
    image: grafana/grafana
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=grafana.batch7.online
      - LETSENCRYPT_HOST=grafana.batch7.online
      - LETSENCRYPT_EMAIL=bonny.ophelie@gmail.com

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    environment:
      - VIRTUAL_PORT=9090
      - PROMETHEUS_VIRTUAL_HOST=prometheus.batch7.online
      - PROMETHEUS_LETSENCRYPT_HOST=prometheus.batch7.online
      - LETSENCRYPT_EMAIL=bonny.ophelie@gmail.com

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    environment:
      - VIRTUAL_PORT=9100
      - VIRTUAL_HOST=node-exporter.batch7.online
      - LETSENCRYPT_HOST=node-exporter.batch7.online
      - LETSENCRYPT_EMAIL=bonny.ophelie@gmail.com

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      - VIRTUAL_PORT=8081
      - VIRTUAL_HOST=cadvisor.batch7.online
      - LETSENCRYPT_HOST=cadvisor.batch7.online
      - LETSENCRYPT_EMAIL=bonny.ophelie@gmail.com

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    environment:
      - VIRTUAL_PORT=9093
      - VIRTUAL_HOST=alertmanager.batch7.online
      - LETSENCRYPT_HOST=alertmanager.batch7.online
      - LETSENCRYPT_EMAIL=bonny.ophelie@gmail.com

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  default:
    external: true
    name: letsencrypt
