- name: Check if Docker is installed
  become: true
  ansible.builtin.command: docker -v
  register: docker_installed
  ignore_errors: true

- name: Install Docker
  become: true
  block:
    - name: Add Docker's official GPG key
      block:
        - name: Update apt
          ansible.builtin.import_role:
            name: update
        - name: Install necessary packages
          become: true
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            state: present
            update_cache: true

        - name: Add GPG key
          ansible.builtin.shell:
            cmd: |
              sudo install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              sudo chmod a+r /etc/apt/keyrings/docker.gpg
          args:
              chdir: /etc/apt/keyrings/
              creates: docker.gpg

    - name: Add the repository to Apt sources
      block:
        - name: Add repos
          ansible.builtin.shell:
            cmd: |
              echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
              "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        - name: Update apt
          ansible.builtin.import_role:
            name: update

    - name: Install Docker packages
      become: true
      when: docker_installed.failed
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: Ensure Docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present
  register: docker_group

- name: Add User to docker group
  become: true
  when: docker_group is changed
  ansible.builtin.user:
    name: yourUser
    groups: docker
    append: true

- name: Copy docker-compose folder
  ansible.builtin.copy:
    src: ./monitoring
    dest: /home/admin