- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: restarted
  
- name: Reload ufw
  ansible.builtin.service:
      name: ufw
      state: reloaded
